apiVersion: v1
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: kafka
  spec:
    replicas: 1
    selector:
      deploymentconfig: kafka
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: kafka
      spec:
        containers:
        - env:
          - name: KAFKA_ADVERTISED_HOST_NAME
            value: kafka
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_DELETE_TOPIC_ENABLE
            value: "true"
          - name: KAFKA_LOG_CLEANER_ENABLE
            value: "false"
          - name: KAFKA_LOG_RETENTION_HOURS
            value: "2147483647"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: zookeeper:2181
          image: 172.30.1.1:5000/strato/blockapps-silo-kafka:latest
          name: blockapps-silo-kafka
          ports:
          - containerPort: 9092
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - kafka
        from:
          kind: ImageStreamTag
          name: blockapps-silo-kafka:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: kafka
  spec:
    ports:
    - name: 9092-tcp
      port: 9092
      targetPort: 9092
    selector:
      deploymentconfig: kafka
  status:
    loadBalancer: {}
kind: List
metadata: {}
